apiVersion: ziti.crossplane.io/v1alpha1
kind: AuthPolicy
metadata:
  name: certificates-only
spec:
  providerConfigRef:
    kind: ProviderConfig
    name: default
  forProvider:
    name: certificates-only
    primary:
      cert:
        allowed: true
        allowExpiredCerts: false
      updb:
        allowed: false
      extJwt:
        allowed: false
