apiVersion: ziti.crossplane.io/v1alpha1
kind: Service
metadata:
  name: service-sticky
  namespace: default
spec:
  forProvider:
    encryptionRequired: true
    name: service-sticky
    terminatorStrategy: sticky
  managementPolicies:
    - '*'
  providerConfigRef:
    kind: ProviderConfig
    name: default

