apiVersion: ziti.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  # Ziti Controller URL
  host: https://controller.example.com:441
  # Password authentication
  username: admin
  password: supersecret
  # OR Certificate authentication (uncomment and comment out username/password):
  # cert: |
  #   -----BEGIN CERTIFICATE-----
  #   MIID...
  #   -----END CERTIFICATE-----
  # key: |
  #   -----BEGIN RSA PRIVATE KEY-----
  #   MIIE...
  #   -----END RSA PRIVATE KEY-----
  # ca: |
  #   -----BEGIN CERTIFICATE-----
  #   MIID...
  #   -----END CERTIFICATE-----
