/*
Copyright 2025 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command docs writes the reference pages of docs/resources and docs/fields.md
// from the generated CRDs, the examples and the notes next to this file. It
// runs with "make generate"; the pages are never edited by hand.
//
//	go run ./hack/docs <repository root>
package main

import (
	"bufio"
	"bytes"
	"embed"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	utilyaml "k8s.io/apimachinery/pkg/util/yaml"
	"sigs.k8s.io/yaml"
)

//go:embed notes/*.md
var notes embed.FS

const header = "<!-- Generated by hack/docs from package/crds, examples and hack/docs/notes. Do not edit: run \"make generate\". -->\n\n"

// A field is one row of a table of fields.
type field struct {
	Path        string
	Type        string
	Required    bool
	Default     string
	Description string
	// ItemRules are the rules of an item of a list, which span its fields:
	// the table of settings states them after the description of the list.
	ItemRules string
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: docs <repository root>")
		os.Exit(2)
	}
	if err := run(os.Args[1]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(root string) error {
	crds, err := readCRDs(filepath.Join(root, "package", "crds"))
	if err != nil {
		return err
	}
	examples, err := readExamples(root)
	if err != nil {
		return err
	}

	out := filepath.Join(root, "docs", "resources")
	if err := os.RemoveAll(out); err != nil { //nolint:gosec // The directory of the repository named on the command line.
		return err
	}
	if err := os.MkdirAll(out, 0o750); err != nil { //nolint:gosec // As above.
		return err
	}

	index, fields, err := writeKinds(out, crds, examples)
	if err != nil {
		return err
	}
	config, err := renderConfig(crds)
	if err != nil {
		return err
	}
	if err := write(filepath.Join(out, "providerconfig.md"), config); err != nil {
		return err
	}
	if err := write(filepath.Join(out, "README.md"), index); err != nil {
		return err
	}
	return write(filepath.Join(root, "docs", "fields.md"), fields)
}

// writeKinds writes the page of every kind and returns the index of the
// pages and the page of all fields. It takes the kinds it has written out of
// crds.
func writeKinds(out string, crds map[string]*apiextensionsv1.CustomResourceDefinition, examples map[string][]example) (index, fields []byte, err error) {
	f := &bytes.Buffer{}
	f.WriteString(header)
	f.WriteString("# Fields and what they do in Ziti\n\n")
	f.WriteString("Every setting of every kind, with the field of the Ziti Edge Management API\nit ends up in. The page of a kind has the same table with types and\ndefaults, an example and how the kind behaves.\n")

	i := &bytes.Buffer{}
	i.WriteString(header)
	i.WriteString("# Resources\n\n| Kind | In Ziti | Connection secret |\n|------|---------|-------------------|\n")

	for _, k := range kinds {
		crd, ok := crds[k.Kind]
		if !ok {
			return nil, nil, fmt.Errorf("no CRD for kind %s", k.Kind)
		}
		delete(crds, k.Kind)
		page, table, err := render(k, crd, examples[k.Kind])
		if err != nil {
			return nil, nil, err
		}
		name := strings.ToLower(k.Kind) + ".md"
		if err := write(filepath.Join(out, name), page); err != nil {
			return nil, nil, err
		}
		secret := "none"
		if k.Secret != "" {
			secret = "`" + k.Secret + "`"
		}
		fmt.Fprintf(i, "| [`%s`](%s) | %s | %s |\n", k.Kind, name, k.Entity, secret)
		fmt.Fprintf(f, "\n## %s\n\n%s; see [%s](resources/%s).\n\n%s", k.Kind, upperFirst(k.Entity), k.Kind, name, table)
	}
	i.WriteString("\n[`ProviderConfig` and `ClusterProviderConfig`](providerconfig.md) connect the\nprovider to a Ziti controller.\n")
	return i.Bytes(), f.Bytes(), nil
}

func write(path string, content []byte) error {
	return os.WriteFile(path, content, 0o600) //nolint:gosec // A page of the repository named on the command line.
}

// render returns the page of a kind and its table of fields in Ziti.
func render(k kind, crd *apiextensionsv1.CustomResourceDefinition, examples []example) (page []byte, table string, err error) {
	schema := crd.Spec.Versions[0].Schema.OpenAPIV3Schema
	forProvider, ok := schema.Properties["spec"].Properties["forProvider"]
	if !ok {
		return nil, "", fmt.Errorf("kind %s has no spec.forProvider", k.Kind)
	}
	note, err := notes.ReadFile("notes/" + strings.ToLower(k.Kind) + ".md")
	if err != nil {
		return nil, "", fmt.Errorf("kind %s has no notes: %w", k.Kind, err)
	}

	b := &bytes.Buffer{}
	b.WriteString(header)
	fmt.Fprintf(b, "# %s\n\n%s\n\n", k.Kind, paragraph(schema.Description))
	renderSummary(b, k, crd)
	if err := renderExample(b, k, examples); err != nil {
		return nil, "", err
	}
	table = renderSettings(b, k, forProvider)
	renderStatus(b, schema.Properties["status"].Properties["atProvider"])
	fmt.Fprintf(b, "\n%s\n", strings.TrimSpace(string(note)))
	return b.Bytes(), table, nil
}

// renderSummary writes what the kind is in Ziti.
func renderSummary(b *bytes.Buffer, k kind, crd *apiextensionsv1.CustomResourceDefinition) {
	b.WriteString("| | |\n|---|---|\n")
	fmt.Fprintf(b, "| API version | `%s/%s` |\n", crd.Spec.Group, crd.Spec.Versions[0].Name)
	fmt.Fprintf(b, "| Scope | %s |\n", crd.Spec.Scope)
	fmt.Fprintf(b, "| In Ziti | %s, `/edge/management/v1/%s` |\n", k.Entity, k.Collection)
	if k.Replace {
		b.WriteString("| Updated with | `PUT`: a setting that is left out of the spec is reset to the default of Ziti |\n")
	} else {
		b.WriteString("| Updated with | `PATCH`: a setting that is left out of the spec is left alone in Ziti |\n")
	}
	if k.Secret != "" {
		fmt.Fprintf(b, "| Connection secret | `%s`, in the Secret of `spec.writeConnectionSecretToRef` |\n", k.Secret)
	}
}

// renderExample writes the manifest of the example of the kind and lists the
// other examples that have the kind.
func renderExample(b *bytes.Buffer, k kind, examples []example) error {
	if len(examples) == 0 {
		return fmt.Errorf("kind %s has no example", k.Kind)
	}
	shown := examples[0]
	for _, e := range examples {
		if e.Path == k.Example {
			shown = e
		}
	}
	if k.Example != "" && shown.Path != k.Example {
		return fmt.Errorf("kind %s: %s has no manifest of the kind", k.Kind, k.Example)
	}
	fmt.Fprintf(b, "\n## Example\n\nFrom [`%s`](../../%s):\n\n```yaml\n%s\n```\n", shown.Path, shown.Path, strings.TrimSpace(shown.Manifest))

	var others []string
	seen := map[string]bool{shown.Path: true}
	for _, e := range examples {
		if !seen[e.Path] {
			seen[e.Path] = true
			others = append(others, fmt.Sprintf("[`%s`](../../%s)", e.Path, e.Path))
		}
	}
	if len(others) > 0 {
		fmt.Fprintf(b, "\nMore manifests of the kind: %s.\n", strings.Join(others, ", "))
	}
	return nil
}

// renderSettings writes the table of spec.forProvider and returns the short
// form of it for the page of all fields.
func renderSettings(b *bytes.Buffer, k kind, forProvider apiextensionsv1.JSONSchemaProps) string {
	b.WriteString("\n## Settings: `spec.forProvider`\n\n")
	b.WriteString("| Field | Type | Default | Field in Ziti | What it does in Ziti |\n|-------|------|---------|---------------|----------------------|\n")
	t := &strings.Builder{}
	t.WriteString("| Field | Field in Ziti | What it does in Ziti |\n|-------|---------------|----------------------|\n")
	for _, f := range flatten(forProvider, "") {
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s |\n", f.Path, f.typ(), code(f.Default), k.inZiti(f.Path), cell(f.Description+f.ItemRules))
		fmt.Fprintf(t, "| `%s` | %s | %s |\n", f.Path, k.inZiti(f.Path), cell(f.Description+f.ItemRules))
	}
	if k.Constant != "" {
		fmt.Fprintf(b, "\nThe provider also sends %s.\n", k.Constant)
	}
	b.WriteString("\nThe settings every managed resource has, such as `spec.providerConfigRef`,\n`spec.managementPolicies` and `spec.writeConnectionSecretToRef`, are described\nin [Concepts](../concepts.md).\n")
	return t.String()
}

// renderStatus writes the table of status.atProvider.
func renderStatus(b *bytes.Buffer, atProvider apiextensionsv1.JSONSchemaProps) {
	b.WriteString("\n## Status: `status.atProvider`\n\n| Field | Type | What it shows |\n|-------|------|---------------|\n")
	for _, f := range flatten(atProvider, "") {
		description := f.Description
		if description == "" {
			description = "As Ziti reports it."
		}
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", f.Path, f.Type, cell(description))
	}
}

// renderConfig returns the page of the two kinds of provider configuration.
// Nothing but them and their usages may be left of the CRDs.
func renderConfig(crds map[string]*apiextensionsv1.CustomResourceDefinition) ([]byte, error) {
	for name := range crds {
		if !strings.Contains(name, "ProviderConfig") {
			return nil, fmt.Errorf("kind %s has no entry in hack/docs/kinds.go", name)
		}
	}
	crd := crds["ProviderConfig"]
	if crd == nil {
		return nil, errors.New("no CRD for kind ProviderConfig")
	}
	note, err := notes.ReadFile("notes/providerconfig.md")
	if err != nil {
		return nil, err
	}
	parts := strings.SplitN(string(note), "<!-- fields -->", 2)
	if len(parts) != 2 {
		return nil, errors.New("notes/providerconfig.md has no <!-- fields --> marker")
	}

	b := &bytes.Buffer{}
	b.WriteString(header)
	b.WriteString("# ProviderConfig and ClusterProviderConfig\n\n")
	b.WriteString(strings.TrimSpace(parts[0]))
	b.WriteString("\n\n## Settings: `spec`\n\n| Field | Type | Default | What it does |\n|-------|------|---------|--------------|\n")
	for _, f := range flatten(crd.Spec.Versions[0].Schema.OpenAPIV3Schema.Properties["spec"], "") {
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", f.Path, f.typ(), code(f.Default), cell(f.Description))
	}
	fmt.Fprintf(b, "\n%s\n", strings.TrimSpace(parts[1]))
	return b.Bytes(), nil
}

// typ returns the type of the field, and whether it is required.
func (f field) typ() string {
	if f.Required {
		return f.Type + ", required"
	}
	return f.Type
}

// flatten lists the fields of a schema, nested ones under dotted paths: the
// name first, then the required fields, then the others by name.
func flatten(s apiextensionsv1.JSONSchemaProps, prefix string) []field {
	required := map[string]bool{}
	for _, name := range s.Required {
		required[name] = true
	}
	names := make([]string, 0, len(s.Properties))
	for name := range s.Properties {
		names = append(names, name)
	}
	rank := func(name string) int {
		switch {
		case name == "name":
			return 0
		case required[name]:
			return 1
		}
		return 2
	}
	sort.Slice(names, func(i, j int) bool {
		if rank(names[i]) != rank(names[j]) {
			return rank(names[i]) < rank(names[j])
		}
		return names[i] < names[j]
	})

	fields := make([]field, 0, len(names))
	for _, name := range names {
		p := s.Properties[name]
		f := field{Path: prefix + name, Type: p.Type, Required: required[name], Description: describe(p)}
		if p.Default != nil {
			f.Default = strings.Trim(string(p.Default.Raw), `"`)
		}
		fields = append(fields, nested(f, p)...)
	}
	return fields
}

// nested returns the field with the type of what it holds, followed by the
// fields it holds.
func nested(f field, p apiextensionsv1.JSONSchemaProps) []field {
	switch {
	case p.Type == "array" && p.Items != nil && p.Items.Schema != nil:
		f.Type = "list of " + p.Items.Schema.Type + "s"
		if len(p.Items.Schema.Enum) > 0 {
			f.Description += " " + enum(p.Items.Schema.Enum)
		}
		f.ItemRules = itemRules(*p.Items.Schema)
		return append([]field{f}, flatten(*p.Items.Schema, f.Path+"[].")...)
	case p.Type == "object" && p.AdditionalProperties != nil && p.AdditionalProperties.Schema != nil:
		f.Type = "map of " + p.AdditionalProperties.Schema.Type + "s"
		return []field{f}
	case p.Type == "object":
		return append([]field{f}, flatten(p, f.Path+".")...)
	}
	return []field{f}
}

// itemRules returns the rules of an item of a list as sentences that follow
// the description of the list.
func itemRules(item apiextensionsv1.JSONSchemaProps) string {
	rules := ""
	for _, rule := range item.XValidations {
		if rule.Message != "" {
			rules += " Rule of an item: " + rule.Message + "."
		}
	}
	return rules
}

// describe returns the description of a field with what its schema enforces.
func describe(p apiextensionsv1.JSONSchemaProps) string {
	parts := []string{paragraph(p.Description)}
	if len(p.Enum) > 0 {
		parts = append(parts, enum(p.Enum))
	}
	switch {
	case p.Minimum != nil && p.Maximum != nil:
		parts = append(parts, fmt.Sprintf("From %v to %v.", *p.Minimum, *p.Maximum))
	case p.Minimum != nil:
		parts = append(parts, fmt.Sprintf("At least %v.", *p.Minimum))
	case p.Maximum != nil:
		parts = append(parts, fmt.Sprintf("At most %v.", *p.Maximum))
	}
	if p.Pattern != "" {
		parts = append(parts, fmt.Sprintf("Must match `%s`.", p.Pattern))
	}
	for _, rule := range p.XValidations {
		// A rule the description states already, after the name of the
		// field, is not repeated.
		_, stated, _ := strings.Cut(rule.Message, " ")
		if rule.Message != "" && !strings.Contains(parts[0], stated) {
			parts = append(parts, "Rule: "+rule.Message+".")
		}
	}
	return strings.TrimSpace(strings.Join(parts, " "))
}

func enum(values []apiextensionsv1.JSON) string {
	names := make([]string, 0, len(values))
	for _, v := range values {
		names = append(names, "`"+strings.Trim(string(v.Raw), `"`)+"`")
	}
	return "One of " + strings.Join(names, ", ") + "."
}

// paragraph joins the lines of a description.
func paragraph(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// cell escapes what would break a table cell.
func cell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}

func code(s string) string {
	if s == "" {
		return ""
	}
	return "`" + s + "`"
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func readCRDs(dir string) (map[string]*apiextensionsv1.CustomResourceDefinition, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.yaml"))
	if err != nil {
		return nil, err
	}
	crds := map[string]*apiextensionsv1.CustomResourceDefinition{}
	for _, path := range paths {
		raw, err := os.ReadFile(path) //nolint:gosec // Reads generated manifests of this repository.
		if err != nil {
			return nil, err
		}
		crd := &apiextensionsv1.CustomResourceDefinition{}
		if err := yaml.Unmarshal(raw, crd); err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		crds[crd.Spec.Names.Kind] = crd
	}
	return crds, nil
}

// An example is one manifest of an example file.
type example struct {
	Path     string
	Manifest string
}

// readExamples returns the manifests in examples/ by kind, in the order of
// their paths.
func readExamples(root string) (map[string][]example, error) {
	examples := map[string][]example{}
	walk := func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || filepath.Ext(path) != ".yaml" {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		raw, err := os.ReadFile(path) //nolint:gosec // Reads example manifests of this repository.
		if err != nil {
			return err
		}
		if err := manifests(raw, filepath.ToSlash(rel), examples); err != nil {
			return fmt.Errorf("%s: %w", rel, err)
		}
		return nil
	}
	err := filepath.WalkDir(filepath.Join(root, "examples"), walk) //nolint:gosec // The directory of the repository named on the command line.
	return examples, err
}

// manifests adds the manifests of the provider kinds in a file to examples.
func manifests(raw []byte, path string, examples map[string][]example) error {
	reader := utilyaml.NewYAMLReader(bufio.NewReader(bytes.NewReader(raw)))
	for {
		doc, err := reader.Read()
		if errors.Is(err, io.EOF) {
			return nil
		}
		if err != nil {
			return err
		}
		var meta struct {
			APIVersion string `json:"apiVersion"`
			Kind       string `json:"kind"`
		}
		if err := yaml.Unmarshal(doc, &meta); err != nil {
			return err
		}
		if strings.HasPrefix(meta.APIVersion, "ziti.crossplane.io/") {
			examples[meta.Kind] = append(examples[meta.Kind], example{Path: path, Manifest: string(doc)})
		}
	}
}
